### ISSUE TITLE
Detailed statuses

### ISSUE THREAD

**Issue by eloycoto** [Hyperfoil/Hyperfoil#134]
Hi!

In our testsuite, a 403 can be a valid status metric, and 408 can be a invalid
metric. With the current stats is not possible to know the number of status.

Could we got a extended stats information, dump in json, or something similar
like this:
```
PHASE     METRIC    THROUGHPUT    REQUESTS  MEAN      p50       p90       p99       p99.9     p99.99     2xx      3xx  4xx  5xx  CACHE  TIMEOUTS  ERRORS  BLOCKED
loadTest  GET       479.78 req/s   5182200  13.65 ms  11.14 ms  20.19 ms  54.53 ms  90.70 ms  204.47 ms  5182200    0    0    0      0         0       0     0 ns
loadTest  POST      479.78 req/s   5182200  13.64 ms  11.14 ms  20.19 ms  54.26 ms  90.18 ms  204.47 ms  5182200    0    0    0      0         0       0     0 ns
loadTest  sso       8.00 req/s     86390    14.03 ms  12.98 ms  18.74 ms  34.60 ms  95.94 ms  364.90 ms    86370    0   20    0      0         0      16     0 ns
```

To be something like this:
```
{
  "loadtest":[
    {
      "metric": "GET",
      "THROUGHPUT": 1,
      "REQUESTS": XX,
      "MEAN": XX
      "PXX": XX,
      "status": {
        200: XX,
        201: XX,
        403: XX,
        408: XX
      }
    },
    {
      "metric": "POST",
      "THROUGHPUT": 1,
      "REQUESTS": XX,
      "MEAN": XX
      "PXX": XX,
      "status": {
        200: XX,
        201: XX,
        403: XX,
        408: XX
      }
    }
  ]
}
```

This will help out scenario quite a lot, because a JWT token expired, is
something normal, and it's a 403 :-)

Regards

**Comment by rvansa** [comment]
In order to NOT mark 403s as invalid, set `ergonomics.autoRangeCheck` to `false`: https://hyperfoil.io/userguide/benchmark/ergonomics.html (similar option for individual request is on the handler: https://hyperfoil.io/docs/steps/step_httpRequest.html#handler )
You can mark 408s back as invalid by providing your own status handler - `range`: https://hyperfoil.io/docs/steps/step_httpRequest.html#handlerstatusrange (or multiple ones if you need more ranges).

To get detailed stats on different statuses add the `stats` handler: https://hyperfoil.io/docs/steps/step_httpRequest.html#handlerstatus You will then see a `custom` section in the stats JSON (not just expanded status), though.

Could you describe where have you looked in the documentation for answers? I would like to improve our docs but need some insight into how people use that and why they can't find the information.

**Comment by eloycoto** [comment]
works for me, thanks!
