### ISSUE TITLE
Can not fetch stats after controller restart

### ISSUE THREAD

**Issue by matskiv** [Hyperfoil/Hyperfoil#149]
After the controller is restarted, I get 404 error when I try to get stats of a run that finished before the controller restart.

> [hyperfoil@ec2-54-152-21-72]$ stats 0038
ERROR: Server responded with unexpected code: 404, Not Found
Cannot fetch stats for run 0038

Since all the data about runs are still on disk (and "runs" CLI command returns all of the runs), I would expect the controller to be able to provide me the statistics of older runs.

**Comment by rvansa** [comment]
Thanks, I am aware of this. The thing is that Hyperfoil is not intended to be a permanent storage of performance results: we're developing an independent project [Horreum](https://github.com/Hyperfoil/Horreum/) for that. You're right that it might be confusing when `runs` knows about those - it goes through the `info.json` files to find out the highest `runId` so that runs don't mix up. And something more specific than 404 could be more suitable.

There's actually an oposite issue: controller keeps statistics in memory (in addition to disk) and if it were running for long enough it could run out of memory. It should keep at most X results in memory or throw them away after Y hours.

`/run/:runId/stats/all` should already work since it serves data from disk; the other endpoints serve data directly from memory and therefore we would have to load them back up. Since (again) Hyperfoil is not a results repository, I am reluctant to spend time implementing that, though I'd accept contribution.

What I will actually do is add proper explanatory message ('yeah, the run's there but I won't load it for you - fetch stats/all') and provide explanatory hints to CLI.

**Comment by austincunningham** [comment]
@rvansa is the `/run/:runId/stats/total` still available in this case or does this pull from memory also ?

**Comment by rvansa** [comment]
@austincunningham This is served from memory as well:
https://github.com/Hyperfoil/Hyperfoil/blob/master/clustering/src/main/java/io/hyperfoil/clustering/ControllerServer.java#L611

**Comment by austincunningham** [comment]
Thanks @rvansa

**Comment by matskiv** [comment]
> There's actually an oposite issue: controller keeps statistics in memory (in addition to disk) and if it were running for long enough it could run out of memory. It should keep at most X results in memory or throw them away after Y hours.

@rvansa That's actually what caused the controller restart in my case. If HF would be able to serve all /stats/* from disk, then it would be okay to purge the data from memory after a run finishes. Wouldn't his solve both problems?
Or is it kept in memory for performance reasons?

P.S.: I will take a look at Horreum. Thanks.

**Comment by rvansa** [comment]
@matskiv I don't consider performance of controller critical at all as long as it isn't really inconvenient to users (can we load that within one second?). Yes, being able to load it would allow as to drop the data right after we write them to disk.

**Comment by rvansa** [comment]
In the end I've implemented this, however it has certain limits. Hyperfoil stores the response latency in a histogram; the mean, percentiles etc. are just derived statistics. However when writing this down to `all.json` we persist the histogram with higher granularity, in particular with 1 ms precision, and with `percentileTicksPerHalfDistance` of 5 (5 buckets for 50% of fastest requests, 5 buckets for 25% of the next ones...). It's not possible to truly rebuild the histogram, esp. if you have only few requests.
