### ISSUE TITLE
Add FAQ about test execution time for wrk/wrk2 scripts

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#155]
I have had questions about the correlation between the duration `-d` parameter and the time it takes to run a test.  I can not see anything documented wrt the time it takes to execute a test and the requested duration, i.e. if a SUT is saturated, the run time for the benchmark can be longer than the duration set. 

A note in the FAQ would be sufficient so we can guide pple there

**Comment by johnaohara** [comment]
Esp. when requests are blocked, hit max sessions.  am looking at a test atm that had a duration set of 1m. but took 10m for Hyperfoil to complete.

**Comment by rvansa** [comment]
If you're worried about benchmark taking too long we can set `maxDuration`:

https://github.com/Hyperfoil/Hyperfoil/blob/master/cli/src/main/java/io/hyperfoil/cli/commands/WrkAbstract.java#L288

That should stop the sessions even if these are being blocked. I would set that to `duration + timeout`, WDYT?

**Comment by johnaohara** [comment]
That might not be a bad idea, it was a comment that somebody made about setting duration to 1m and it took 10m as all the sessions were blocked (k8's had restarted the pod that was under load) and they could not find anything in the docs to explain why the benchmark was not completing in 1m.

Adding a timeout would probably help in this instance as the sessions were blocked and the results were invalid anyway. Could it be possible to check if sessions were blocked at the end of the run and then cancel if the benchmark is running over and sessions are blocked?

**Comment by rvansa** [comment]
WDYM by 'at the end of the run'? The end of the run is when the phase completes and that happens only after those 10m. You could terminate it after arbitrary time (1m + delta) using the `maxDuration`. While you're right that run that looks stuck is bad I don't see a point in checking if the sessions are blocked - and btw. being blocked is not any kind of state (so you can't easily check it). Those sessions were (probably) trying to fetch a connection from a connection pool and could not find any, so these reported that in statistics and went idle.

**Comment by johnaohara** [comment]
in this context by "end of run" I mean at the end of the user specified duration `-d` 

I was trying to convey that we should not terminate a run prematurely (i.e. before all response have returned) if the requests are progressing without being blocked. Setting a maxDuration might terminate a run if there are outstanding responses, but the load is scaled correctly (i.e. sessions are not blocked) but the SUT is slow to respond .

If we can't easily detect that, then a `maxDuration` is probably acceptable. Would `maxDuration` be proportional to `duration`? i,e, duration+10%?

**Comment by rvansa** [comment]
If the sessions are not blocked on connections, each should send the request within `duration`. As there's individual timeout on each request `timeout` (default 60s) all response should be received within `duration + timeout` as I've initially suggested. I don't think that percentage of original duration is a good measure, since users expect (at first) that the benchmark will really terminate exactly after duration. If you extend duration it's because you want more stable numbers, and the tail of responses should not increase proportionally.

I would really prefer to avoid any 'extra' detection - what `wrk` does should translate to scenario definition. Also the concept of validating that all sessions are in some state is problematic (what if there's one happy session?).

We could have an option on httpRequest to fail the session prematurely if it blocks on connections (however I am not sure how should it report that - it's not an error in response, there's no matching request...).

**Comment by johnaohara** [comment]
@rvansa the change that you pushed looks good 

What happens when a benchmark times out? is there an error/warning logged?

**Comment by rvansa** [comment]
Not at this moment. There will be only general message on INFO level about terminating that phase. Wrk wouldn't print anything either, just report statistics, would it?

**Comment by johnaohara** [comment]
That's a good point, wrk would just print stats. We are emulating wrk/wrk2 so we shouldn't be doing anything different

**Comment by rvansa** [comment]
Closing this issue. If you think there should be anything else added/changed please reopen.
