### ISSUE TITLE
Add SLA to metrics from extensions

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/Hyperfoil#204]
knative-eventing uses an extension to measure the event delivery times. We want to increase throughput until the events exceed an SLA but currently the SLA is only applied to the HF sendEvents.
[receiver.log](https://github.com/Hyperfoil/Hyperfoil/files/7366001/receiver.log)
.

**Comment by willr3** [comment]
It works great. When does SLA violation end a run? We had a rampUp with SLA failures then a steadyState with failures before the run ended. Is there a timer that checks to end a run?

**Comment by rvansa** [comment]
So the stats can be validated when these arrive from all agents. If you have two phases linked with `startAfter` (as staircase does), the rampUp *finishes* (meaning that it won't fire any further requests), then waits until all responses come (or timeout) and then it *terminates*. Only after that it can be sure that no further stats come. The steadyState starts immediately when the rampUp finishes as we don't want any gaps in the load, and it won't be forcefully cancelled - controller cancels only non-started phases.
With auxiliary nodes (the receiver) it is a bit more complicated - since the receiver can't know when it receives all values it periodically sends requests to delay SLA validation for another 10 seconds as long as there are more events coming.

So you will see another phase started in any case; only think I could do is to forcefully terminate it before its duration.

**Comment by rvansa** [comment]
Implemented in 3f8d6caea414045a6bb36ef97b11780eacada293 , closing
