### ISSUE TITLE
Schema URL does not work

### ISSUE THREAD

**Issue by yawkat** [Hyperfoil/Hyperfoil#341]
https://hyperfoil.io/schema is broken.

**Comment by lampajr** [comment]
Hi @yawkat, do you mean that it is broken because it does not referenceany json schem as suggested here https://hyperfoil.io/docs/editor.html ?

I think the correct way to reference the URL accessible JSON schema is using `https://hyperfoil.io/schema.json`:
```
    "yaml.schemas" : {
        "https://hyperfoil.io/schema.json" : "/*.hf.yaml"
    },
```

Did you find `https://hyperfoil.io/schema` referenced somewhere in the doc?

**Comment by yawkat** [comment]
the schema itself references https://hyperfoil.io/schema as its `$id`. it's also listed in https://github.com/Hyperfoil/Hyperfoil/blob/master/RELEASE.md

**Comment by lampajr** [comment]
You are right, I missed the one on the `RELEASE.md` which is actually saying 
[`In order to properly redirect from http://hyperfoil.io/schema to the JSON file we need to add this Front Matter to the beginning of the file`](https://github.com/Hyperfoil/Hyperfoil/blob/master/RELEASE.md#:~:text=In%20order%20to%20properly%20redirect%20from%20http%3A//hyperfoil.io/schema%20to%20the%20JSON%20file%20we%20need%20to%20add%20this%20Front%20Matter%20to%20the%20beginning%20of%20the%20file%3A) but it seems not working :confused:. I will try to take a look at that.

In the meantime I think the workaround is to use the same URL with `.json` suffix: `https://hyperfoil.io/schema.json`.
