### ISSUE TITLE
Enable ipv6 support `in-vm`

### ISSUE THREAD

**Issue by helio-frota** [Hyperfoil/Hyperfoil#346]
After a good investigation work @franz1981 found this https://github.com/trustification/trustify/discussions/214#discussioncomment-9460667

I'm not sure the best way to handle this if is better to document or implement something. I defer for hyperfoil team

thanks for the good work

**Comment by franz1981** [comment]
@willr3 @jabolina qq for you folks: I see that @rvansa has enabled `preferIPv4Stack=true` pretty much everywhere to save the clustering to break: any hint why this could cause any harm? maybe related to jgroup IPv6 support?

**Comment by wburns** [comment]
This has always been just a standard setting in JGroups as IPv6 and JGroups hasn't worked in many various JDKs. http://www.jgroups.org/tutorial/html/ch01.html See section 1.6. 

@belaban, would know for sure but iirc it was due to multicasting and IPv6 compatibilities. Hyperfoil uses TCP only as it has TCPPING so IPv6 should be fine. I think it should be safe to remove it.

If necessary users can always supply the option themselves via JAVA_OPTS environment variable.

**Comment by franz1981** [comment]
Ok so it's time to let this go: many thanks @wburns 
tomorrow I'll send a PR to remove it, and see if your clustering test will survive :P

**Comment by belaban** [comment]
I removed the `-Djava.net.preferIPv4Stack=true` from all scripts a long time ago, [1] describes how JGroups picks the type of addresses it uses.

[1] http://www.jgroups.org/manual5/index.html#IPAddresses

**Comment by franz1981** [comment]
many thanks @belaban and happy to hear from you, bud :)

**Comment by belaban** [comment]
+1!
