### ISSUE TITLE
Wrk/Wrk2 retained dead objects across phases

### ISSUE THREAD

**Issue by franz1981** [Hyperfoil/Hyperfoil#389]
Performing an heap dump of wrk2 while in the `test` phase reveal that "calibaration" allocated `Sessions` and objects are still retained in the heap, bloating the old generation.
It  would be great to further reduce the `wrk/wrk2` memory requirement by "fixing" this, cutting it in half (or more if we decide to save allocating 15X throughput sessions too!)

**Comment by lampajr** [comment]
Hi @franz1981 I tried as well and I can confirm your finding!

First of all given that we have 2 phases (**calibration** and **test**) the overall number of session is doubled, e.g., with `-c 10 -R 1000` and given that the `maxSession` is set to `15 * rate` we end up with `15k` session per phase (i.e., `30k`).

Just as an example I tried to merge the 2 phase into a single phase with 2 `initialSequences` and it shows already a hug improvement in terms of allocation _but_ it reduce its usability as the user now cannot identify calibration and test results.

So I think that keeping 2 separate phase is a must have unless we see alternatives that are feature-equivalent from the user persepctive.

Thus, I see two options here:
- Reduce the number of `maxSessions`, as you are suggesting and I think this would be mostly a heurstic that we should determine 
- Manually perform the GC after the calibration phase such that we can try to cleanup old objects (here we should check if some objects are there because still referenced somewhere, as we were discussing yesterday)

**Comment by franz1981** [comment]
Thanks for checking @lampajr !
I would rather think on a way to make a single phase of it, which is ignoring statistics coming from the first X seconds - if required, or explore native compilation for Hyperfoil.
Both would address the same problem i.e. warming up the JIT to avoid weird pauses and slowdown due to JIT cost or just cold running code.

**Comment by lampajr** [comment]
> Thanks for checking @lampajr !
> I would rather think on a way to make a single phase of it, which is ignoring or marking differently the statistics coming from the first X seconds or explore native compilation for Hyperfoil.
> Both would address the same problem i.e. warming up the JIT to avoid weird pauses and slowdown due to JIT cost or just cold running code.
> 
> Given that we are mostly GC freeish in the hot path, we do not fear the GC activity - and having something which is immediately fast is appealing, and would save users to guess why they setup wrk to run for 10 seconds and getting 16 instead.

I definitely agree with you, I think that spending some time investigating the native compilation for Hyperfoil is totally worth!

**Comment by lampajr** [comment]
As we discussed it might be interesting investigating whether using 2 different runs (1 for the calibration, 1 for the test) but with one single phase each can do the trick. Obviously we should be able to manually run the GC just before the test run starts (so we should consider exposing the GC method currently used during phase initialization)

> NOTE: this is opposed to the current implementation which is 1 run with 2 phases.

**Comment by franz1981** [comment]
This can be closed via https://github.com/Hyperfoil/Hyperfoil/pull/400
