### ISSUE TITLE
Handling HTTP response codes

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#87]
In [Quickstart 2](https://hyperfoil.github.io/quickstart/quickstart2.html) I found a http response code handler:
```
handler:
  # We'll check that the response was successful (status 200-299)
  status:
     range: 2xx
```
I can't find this in benchmark definition doc, so not sure what exactly does it do, but I tried it.
I put this in my benchmark and run it against non-deployed openshift service. Openshift did responde to all hyperfoil's requests with 502 (Service unavailable) or 408 (Request timed out). But hyperfoil doesn't seem to care. 
I received no error nor warning and I got a nice performance report with measurements - also no error or failures present. It says that number of 5xx request is something high and 2xx = 0 but that is pretty much all.

Hyperfoil should react to response codes and throw some error/warning if http.host is not responding properly.

**Comment by rvansa** [comment]
The documentation is here: https://hyperfoil.github.io/docs/steps/step_httpRequest.html#handlerstatusrange

I admit that the status checks do not have a definite place, as in the past there were distinct validators and handlers. This handler in particular calls `Request.markInvalid()` and this increases number of invalid requests in statistics. This does not actually trigger anything, but all 4xx and 5xx responses are reported as errors.

What you're looking for is  [SLA.errorRatio](https://hyperfoil.github.io/docs/steps/step_httpRequest.html#sla). Right now the default is 1.0 - all request may end as errors. You're right that it might make sense to change the default to 0.0 (not allowing any errors) and force user to set an acceptable ratio.

**Comment by rvansa** [comment]
We might also add SLA for invalid requests.

**Comment by mocenas** [comment]
I've added this to my httpRequest:
```
- httpRequest:
    handler:
      status:
        range: 2xx
    sla:
      errorRatio: 0.0
```
And still no change. In report, there is status_2xx: 0, status_5xx: 25000, and that's all. 

I'm trying to say, that the test execution should be able to interrupt, if it finds out, that there is no meaning in doing the tests.
Consider e.g. scenario, that we have benchmark for soak tests, which run e. g. for 8 hours, and after this we find in report that all requests failed, due to some server error. So it was 8 hours of wasted machine time.
It would be nice, if I can configure benchmark to only expect 2XX responses, and if any other then fail and end (or possibly there has to be at lest X% of 2XX responses).

**Comment by rvansa** [comment]
What report exactly? If you're looking into the directory with CSV, there's `failures.csv` that should contain some info (and there's something in `all.json`, too). If you're running from CLI, `stats` should print those errors and metrics with SLA failures will be printed in red.
If a phase has SLA failures, all further phases will be cancelled.

SLAs are evaluated only when the phase terminates on all agents since the data from which these ratios etc. are complete. There are also SLAs with windows (you can check what was the errorRatio in last minute) and react, though those do not interupt the phase upon failure (that could be changed).

**Comment by mocenas** [comment]
Sorry that was my fail, I didn't found the section failure in JSON (which I use). 
I have benchmark with 2 phases, both have same SLA. I tried to modify even SLA window. And phase 1 have cca 100 SLA failures, phase 2 started after phase 1, and also have like 100 SLA failures. 

My phase 2 is configured to start after phase 1 via:
```
        startAfter:
          - phase: phase1
```
Should it cancel phase2 in this setup, if SLA in phase1 fails? It does not.

**Comment by rvansa** [comment]
Okay, that's because phase2 does not start *strictly* after phase1 - phase 2 starts as soon as phase1 *finishes*. At that point we don't have all the stats (because some requests from phase1 are not complete yet), but we start phase2 (to avoid a gap when we'd just wait for the requests).

In order to evaluate phase1 SLAs, it must first terminate, then we collect all stats and only then mark everything that was not started yet as failed (therefore phase2 which already commenced is not cancelled). If you had phase3 starting after phase2, that would probably get cancelled.

**Comment by rvansa** [comment]
I was about to suggest using `startAfterStrict` but that wouldn't help in this case, as there would still be some lag for stats collection and evaluation.

Also, we can't interrupt any ongoing phases when we find out that something has failed the SLA; That would break different scenarios with intentionally concurrent phases (which should not be interrupted).

I could look if we could make sure that the information about phase terminating arrives after all stats (so that `startAfterStrict` would work) but I am not sure if it's worth the hassle, as this variant is not ideal. I would rather suggest interleaving 'steady' phases with 'rampups'.

**Comment by mocenas** [comment]
I added phase3 and it was really cancelled. 
It would be nice to wait with phase2 until I know if phase1 was successful. The thing is, I don't know how much time will it take for phase1 to evaluate SLA's, so injecting some steady phase between them is tricky (can't be too short - may not be enough, don̈́t want it to be too long - waste of time).

**Comment by rvansa** [comment]
That's what `startAfterStrict` should do. However, I don't think that it should be used in practice as during the gap where we're waiting for some staggered requests the load to SUT ceases - queues get flushed, memory released etc... It's better to have continuous load all the time, and really consider only stats from phases that are running against 'heated up' SUT. Note that if you have just iterations of single phase, there's an intrinsic `startAfterStrict` dependency (I could elaborate why). That's why the `staircase` scenario type includes those ramp-ups.
The duration of rampup should be at least request timeout (30 seconds by default) + some small delta (seconds) to allow the communication.

**Comment by mocenas** [comment]
So suggested scheme is something like this?
phase1 - warmUp (1 minute)
phase2 - remainWarm (+- 1 minute)
phase3 - do actual test

**Comment by rvansa** [comment]
If you're concerned if the SUT is really running, you could have
phase1 = validation (always: 1 user, hit all endpoints) / any kind of short smoke test
phase2 = warm up
phase3 = actual test

**Comment by rvansa** [comment]
I think this was explained, and a5c0f4b22e4b78cca0be820998b63e6a83f48a8a adds the invalid ratio SLA.
